### ISSUE TITLE
TravisCI build breaks randomly

### ISSUE THREAD

**Issue by pascal-hofmann** [sonata-project/SonataDoctrineMongoDBAdminBundle#153]
TravisCI build breaks randomly with:
> PHP Fatal error: Interface 'Symfony\Component\Security\Acl\Model\DomainObjectInterface' not found in /home/travis/build/sonata-project/SonataDoctrineMongoDBAdminBundle/vendor/sonata-project/admin-bundle/Admin/Admin.php

See:
- https://travis-ci.org/sonata-project/SonataDoctrineMongoDBAdminBundle/builds/96689408
- https://travis-ci.org/sonata-project/SonataDoctrineMongoDBAdminBundle/builds/84504788
- https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/142

(first two builds are for the same code, third link leads to a different PR which also randomly failed.)

**Comment by Id4v** [comment]
@phofmann-trust Problem with symfony/security-acl. Encountered the same problem when installing SonataAdmin/SonataMongoDBAdmin whith Sf3

Package is required in Sf2.8 (or required-dev in Sf3.0) with versions ~2.8|~3.0. 
https://github.com/symfony/symfony/blob/3.0/composer.json#L83

As of today, there is no stable version in 2.8.x or 3.0.x, so the package is not installed and DomainObjectInterface isn't available.

Adding a dependency to `symfony/security-acl : dev-master` fixes this bug but this is clearly a temporary fix, since symfony should install it out of the box.

**Comment by core23** [comment]
This issue should be fixed.
